import { NextResponse } from "next/server";
import { checkRole, createServiceRoleClient, logAuditEvent } from "../utils";

export async function POST(req: Request) {
  // 1. Verify that user has owner or admin role
  const { hasAccess, userId, errorResponse } = await checkRole(req, ["owner", "admin"]);
  if (!hasAccess) return errorResponse!;

  const tenantId = req.headers.get("x-tenant-id")!;

  try {
    const body = await req.json();
    const { role, email, phone, invitee_name, expires_in_days = 7 } = body;

    if (!role) {
      return NextResponse.json({ message: "Role is required" }, { status: 400 });
    }

    const expiresAt = new Date();
    expiresAt.setDate(expiresAt.getDate() + expires_in_days);

    const supabase = createServiceRoleClient();

    // Fetch tenant slug to construct invite link
    const { data: tenant } = await supabase
      .from("tenants")
      .select("slug")
      .eq("id", tenantId)
      .single();

    if (!tenant) {
      return NextResponse.json({ message: "Tenant not found" }, { status: 404 });
    }

    // Insert invitation (token is generated by DB default)
    const { data: invitation, error: insertError } = await supabase
      .from("invitations")
      .insert({
        tenant_id: tenantId,
        created_by: userId,
        role,
        email,
        phone,
        invitee_name,
        expires_at: expiresAt.toISOString(),
      })
      .select()
      .single();

    if (insertError || !invitation) {
      return NextResponse.json(
        { message: insertError?.message || "Failed to generate invitation" },
        { status: 500 }
      );
    }

    // Resolve the request URL or host
    const origin = req.headers.get("origin") || process.env.NEXT_PUBLIC_APP_URL || "https://utsav.app";
    const link = `${origin}/join/${tenant.slug}/${role}/${invitation.token}`;

    // Get active role
    const { data: actorMember } = await supabase
      .from("tenant_members")
      .select("role")
      .eq("tenant_id", tenantId)
      .eq("user_id", userId)
      .single();

    // Log action
    await logAuditEvent({
      tenantId,
      actorId: userId,
      actorRole: actorMember?.role || "admin",
      action: "invite_create",
      entityType: "invitation",
      entityId: invitation.id,
      afterData: invitation,
    });

    return NextResponse.json({
      token: invitation.token,
      link,
      invitation,
    });
  } catch (err: any) {
    return NextResponse.json({ message: err.message }, { status: 500 });
  }
}
